// Common components
export { default as AppInfo } from './common/AppInfo.vue'
export { default as SecurityScoreboard } from './common/SecurityScoreboard.vue'
export { default as ServerLocations } from './common/ServerLocations.vue'
export { default as TrackersComponent } from './common/TrackersComponent.vue'
export { default as UrlsComponent } from './common/UrlsComponent.vue'
export { default as ScanOptions } from './common/ScanOptions.vue'
export { default as SecretsComponent } from './common/SecretsComponent.vue'
export { default as FirebaseAnalysis } from './common/FirebaseAnalysis.vue'
export { default as InfoItem } from './common/InfoItem.vue'
export { default as MalwareLookup } from './common/MalwareLookup.vue'
export { default as ComponentCounter } from './common/ComponentCounter.vue'
export { default as ComponentsSection } from './common/ComponentsSection.vue'
export { default as DomainMalwareCheck } from './common/DomainMalwareCheck.vue'
export { default as EmailsComponent } from './common/EmailsComponent.vue'
export { default as ApplicationPermissions } from './common/ApplicationPermissions.vue'

// Android specific components
export { default as AndroidStringsComponent } from './android/StringsComponent.vue'
export { default as AndroidNetworkSecurity } from './android/NetworkSecurity.vue'
export { default as AndroidPlayStore } from './android/PlayStore.vue'
export { default as AndroidFileAnalysis } from './android/FileAnalysis.vue'
export { default as AndroidManifestAnalysis } from './android/ManifestAnalysis.vue'
export { default as AndroidNIAPAnalysis } from './android/NIAPAnalysis.vue'
export { default as AndroidBrowsableActivities } from './android/BrowsableActivities.vue'
export { default as AndroidCertificateAnalysis } from './android/CertificateAnalysis.vue'
export { default as AndroidCodeAnalysis } from './android/CodeAnalysis.vue'
export { default as AndroidAbusedPermissions } from './android/AbusedPermissions.vue'
export { default as AndroidBehaviourAnalysis } from './android/BehaviourAnalysis.vue'
export { default as AndroidBinaryAnalysis } from './android/BinaryAnalysis.vue'
export { default as AndroidAPI } from './android/APIAndroid.vue'
export { default as AndroidAPKiDAnalysis } from './android/APKiDAnalysis.vue'

// iOS specific components
export { default as iOSStringsComponent } from './iOS/StringsComponent.vue'
export { default as iOSTransportSecurity } from './iOS/TransportSecurity.vue'
export { default as iOSURLSchemes } from './iOS/URLSchemes.vue'
export { default as iOSFileAnalysis } from './iOS/FileAnalysis.vue'
export { default as iOSStaticLibraryAnalysis } from './iOS/StaticLibraryAnalysis.vue'
export { default as iOSBinaryAnalysis } from './iOS/BinaryAnalysis.vue'
export { default as iOSBinaryCodeAnalysis } from './iOS/BinaryCodeAnalysis.vue'
export { default as iOSBinaryInfo } from './iOS/BinaryInfo.vue'
export { default as iOSDylibAnalysis } from './iOS/DylibAnalysis.vue'
